### ISSUE TITLE
generate_dblists.py not Py3 safe

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.db.avspoof#3]
In the code line:
https://github.com/bioidiap/bob.db.avspoof/blob/master/bob/db/avspoof/protocols/generate_dblists.py#L119
there is a ``print`` statement that is not Python 3 compatible. Either use the print function (by having the first line of the script being: ``from __future__ import print_function``) or even better by using the logging module:

```
import bob.core
logger = bob.core.log.setup("bob.db.avspoof")
bob.core.log.set_verbosity_level(logger, 2)
...
logger.info("...")
```

(see http://pythonhosted.org/bob.core/guide.html#logging for more details)

Cheers
Manuel

**Comment by pkorshunov** [comment]
Should be fixed now..
